### ISSUE TITLE
Better Nether server-side crash

### ISSUE THREAD

**Issue by wmboeckman** [CaffeineMC/hydrogen-fabric#10]
**Mod Version:** 0.1.2-SNAPSHOT
**Fabric Version:** 0.10.8

**Issue Description:**
BetterNether  causes a server-side crash when entering the nether.

NOTE: I dont believe this is an issue with hydrogen, but im leaving this here along with the link to the [issue I made on Better Nether's github page](https://github.com/paulevsGitch/BetterNether/issues/260) in order to get more eyes on it.
**Error:**
`java.lang.IllegalArgumentException: Cannot set property class_2746{name=bottom, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:golden_vine}`
**Crash Log:**
[crash-2020-12-08_14.45.04-server.txt](https://github.com/jellysquid3/hydrogen-fabric/files/5662116/crash-2020-12-08_14.45.04-server.txt)

**Comment by linzexin022** [comment]
Met the same problem

**Comment by jellysquid3** [comment]
This issue is now tracked by #19.
