### ISSUE TITLE
Current mod release (0.1.1) doesn't work with 1.16.4

### ISSUE THREAD

**Issue by FavoritoHJS** [CaffeineMC/hydrogen-fabric#11]
This release only works with 1.16.2, while the latest version at the time of writing is 1.16.4.

Changes between these versions are likely not too significant, so porting shouldn't be difficult.

Workaround: Edit the end of fabric.mod.json from
```
  "depends": {
    "fabricloader": ">=0.9.0",
    "minecraft": "1.16.2"
  }
```
 to:
```
   "depends": {
    "fabricloader": ">=0.9.0",
    "minecraft": ">=1.16.2"
  }
```
You can also download a never .jar in Actions, though remember: The cutting edge tends to cut.

**Comment by Dolphin2Point1** [comment]
build the latest commit. a new release may not come for a while.

**Comment by Dbl7id** [comment]
The current release version is 0.1.0 on curseforge, and that version works with 1.16.4 still. Did you grab that build from the discord server?

**Comment by mrmangohands** [comment]
This is the issue tracker for hydrogen, which isn't on curseforge

**Comment by dbl7id** [comment]
dammit my bad I didn't read

**Comment by K0-RR** [comment]
For me it works great on 1.16.4. Just change required minecraft version in fabric.mod.json. In fact this is the most important mod after Sodium for me. Without it my friends wouldn't be able to play my modpack so @jellysquid3 thank You for Your work.

**Comment by DragonEggBedrockBreaking** [comment]
You can download a 1.16.4 version from [github actions](https://github.com/jellysquid3/hydrogen-fabric/suites/1493578797/artifacts/25998798). Note that this, just like all other hydrogen builds, is not 100% stable. 

This is two commits behind. In order to be completely up-to-date, you can either try building yourself or get a build from JellySquid's discord.

Note that 1.16.5 is out now, which complicates things if you want to update...

**Comment by Siuolplex** [comment]
> Note that 1.16.5 is out now, which complicates things if you want to update...

How so? I thought its fixes didnt affect any mods

**Comment by RangoMcRoony** [comment]
To get the latest version of hydrogen working on 1.16.4 I done the same as @FavoritoHJS but instead of "minecraft": ">=1.16.2" I changed it to "minecraft": ">=1.16.4"

**Comment by Genau6502** [comment]
> To get the latest version of hydrogen working on 1.16.4 I done the same as @FavoritoHJS but instead of "minecraft": ">=1.16.2" I changed it to "minecraft": ">=1.16.4"

Why would >=1.16.2 not work?

**Comment by RangoMcRoony** [comment]
@yitzy299 yh Ur right, I know nothing about coding I was just trying to figure it out and it happened to work so I didn't question it lol

**Comment by DragonEggBedrockBreaking** [comment]
Hydrogen has now been officially updated to 1.16.5, so nobody needs to change anything for 1.16.5; just download from [modrinth](https://www.modrinth.com/mod/hydrogen) or [github releases](https://github.com/jellysquid3/hydrogen-fabric/releases). It becomes more difficult if you want to use 1.16.4: You will need to change the version lock. Not too difficult, just change the number from "1.16.5" to "1.16.4". I use it like that (not all of my mods are updated to 1.16.5 yet) and it works, but remember that little/no official support is given if you edit the mod, even in such a seemingly small way.

**Comment by RangoMcRoony** [comment]
@DragonEggBedrockBreaking, thank you for the explanation I really appreciate it. I might just wait till lithium is updated to 1.16.5 then use hydrogen on 1.16.5 too.

Thanks
