### ISSUE TITLE
Crash with "BetterEnd" mod

### ISSUE THREAD

**Issue by shouxd** [CaffeineMC/hydrogen-fabric#12]
https://pastebin.com/tCiMm0Pa

Trying to run Hydrogen mod with BetterEnd results in above crash. When removed, game runs as usual

**Comment by Dolphin2Point1** [comment]
this is also a duplicate of #10, it seems to be the same error.

**Comment by K0-RR** [comment]
I believe this should be closed now as well as #10. Seems like Hydrogen 0.2 fixed this.

**Comment by jellysquid3** [comment]
This issue is now tracked by #19.
