### ISSUE TITLE
BetterNether (And if I am correct BetterEnd as well) are incompatible with Hydrogen

### ISSUE THREAD

**Issue by Kizuati** [CaffeineMC/hydrogen-fabric#15]
[latest.log](https://github.com/jellysquid3/hydrogen-fabric/files/5832318/latest.log)
Crash log with latest release here,generation works fine without it. I talked a bit more about it in the [BetterNether issues](https://github.com/paulevsGitch/BetterNether/issues/281) mentioning another crash with an older version of Hydrogen (from Discord).

**Comment by Kroppeb** [comment]
Hydrogen seems to be removing the `bottom` property of the `golden_vine` block.

**Comment by Dolphin2Point1** [comment]
duplicate of #10
