### ISSUE TITLE
StructurePool constructor will lag and eat RAM like crazy if the element's weight is set to an extreme value

### ISSUE THREAD

**Issue by TelepathicGrunt** [CaffeineMC/hydrogen-fabric#16]
So for jigsaw structures such as villages or outposts, they have what are called pools and in these pools are pieces of the structure with a weight of how often they get picked. What has been reported is that if someone sets a piece's weight to a very high value by datapack or a mod, the game will lag hard when loading up the world and when going to the structure. If the weight is high enough, the JVM will run out of memory!

Now if you check out StructurePool's constructor, you'll see why very fast...
https://hatebin.com/ylpqtmsqkg

Yep. Mojang makes a new instance of the element x number of times with x being the weight and shoves all those separate instances into a list just so they can do a `this.elements.get(random.nextInt(this.elements.size()));` to get a random piece. It's uber cursed lmao 

Here's a datapack to reproduce the issue!
[outofmemory.zip](https://github.com/jellysquid3/lithium-fabric/files/5461353/outofmemory.zip)

And here's the result of the datapack 
![image](https://user-images.githubusercontent.com/40846040/97633792-07a2bc00-1a0b-11eb-85de-a7f8bd6895e1.png)

**Comment by Kroppeb** [comment]
@jellysquid3 Shouldn't this be fixed in Lithium? As the [readme](https://github.com/jellysquid3/hydrogen-fabric#why-are-these-patches-not-in-lithium) says:
> #### Why are these patches not in Lithium?
> Hydrogen relies on rather egregious hacks in order to load some code into the game, primarily because the Guava library developers really do not want people re-implementing their interfaces. These hacks are "safe" in the sense that the game will simply fail to start if a problem occurs, but are really rather not suitable for the standards which Lithium intends to promote. In other words, this mod could be looked at as "things too dirty to put in Lithium."

**Comment by Kroppeb** [comment]
Sadly this is not fixable. 
Here is my explanation from [Mojira](https://bugs.mojang.com/browse/MC-203131?focusedCommentId=904287&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-904287), but with yarn mappings.
> I did some code analysis in the hopes of fixing this in lithium. Sadly it seems impossible to avoid allocating a list/array containing all the elements without changing how current structures would generate in the new codebase.
In
`net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator#generatePiece(net.minecraft.structure.PoolStructurePiece, org.apache.commons.lang3.mutable.MutableObject, int, int, boolean)`
2 calls are made to 
`net.minecraft.structure.pool.StructurePool#getElementIndicesInRandomOrder(java.util.Random)` 
This method uses ObjectArrays.shuffle. It's impossible to generate any chunk of this array without generating the whole array.

> This could be fixed if 1.17 causes worlds to generate differently then in 1.16 in which case changing how structures are generated might be on the table.

**Comment by magneticflux-** [comment]
From a quick discussion on the Discord:
- It *may technically* be possible to lower memory usage by a factor of ~5 (assuming few unique elements) if a lot of effort is put in to use packed integer arrays of indices for the copy-and-shuffle algorithm
- The existing algorithm is really, really, *really*, inefficient and in order to produce the same results as vanilla we'd need to be equally inefficient

The conclusion: "But why though? What horrifying datapack needs this in order to run? Is it even worth it?"

**Comment by TelepathicGrunt** [comment]
I did make my Blame mod be able to detect when any mod or datapack tries to do a weight of 10000+ for a structure piece. So at the very least, any out-of-memory crash from this inefficiency can quickly be investigated and the offending mod/datapack found with Blame on.

**Comment by jellysquid3** [comment]
Regarding the discussion that was mentioned earlier, I don't think that this is worth optimizing. There are tricks that could be used to reduce the memory usage but we're still dealing with O(n) memory requirements. It doesn't appear to be possible for us to change the algorithm to fix these problems without inadvertently changing what items get returned, which would be a breaking change that affects world generation severely.
