### ISSUE TITLE
Incompatible with WorldEdit

### ISSUE THREAD

**Issue by Bendimester23** [CaffeineMC/hydrogen-fabric#17]
https://paste.enginehub.org/pRnKwzLN0

when i use the //setbiome, it didn't work.

**Comment by Snivine** [comment]
can confirm this, seems to be the inmutable map of hydrogen causing issues with the world edit part of worldedit

**Comment by coderbot16** [comment]
* Relevant WorldEdit mixin: https://github.com/EngineHub/WorldEdit/blob/f2ce020da059718e34342c149172944dfd02b775/worldedit-fabric/src/main/java/com/sk89q/worldedit/fabric/mixin/MixinBiomeArray.java
* Relevant Hydrogen mixin: https://github.com/CaffeineMC/hydrogen-fabric/blob/d0e8556eacbc531ec262e6b60a89b3c7a291d36b/src/main/java/me/jellysquid/mods/hydrogen/mixin/chunk/MixinBiomeArray.java

The sanest solution for now is probably to copy the configuration system from Lithium, and have WorldEdit disable this patch for the time being. In the future, perhaps there could be better integration between the two mods: WorldEdit could signal to Hydrogen that it needs the unpacked biome array, WorldEdit could do its thing, then Hydrogen could re-pack the biome array.

**Comment by jellysquid3** [comment]
This is no longer relevant for the 1.17.x version (as the patch was implemented into vanilla) so we can close this.
