### ISSUE TITLE
Lithium broke world. 

### ISSUE THREAD

**Issue by K0-RR** [CaffeineMC/hydrogen-fabric#18]
I got a crash while flying in the creative. Like in jellysquid3/lithium-fabric#173 but this time instead of "so much info - cactus is guilty" is the log you can see Terrestria, which indeed adds cactuses. Do you want me to upload the world for you?
https://hatebin.com/mbygditndr

**Comment by jellysquid3** [comment]
This issue is now tracked by #19.
