### ISSUE TITLE
Minecraft Wont Start if JDK 16 Release Canadate 1 is used (With Hydrogen installed)

### ISSUE THREAD

**Issue by Blobanium** [CaffeineMC/hydrogen-fabric#25]
so apparently Minecraft doesn't start with hydrogen if you use JDK 16 Release Canadate 1 As Your Java install

This is what the Log Is Outputting
![Capture](https://user-images.githubusercontent.com/45613796/107826640-0f783900-6d3a-11eb-8b6c-2a8e7deb4339.PNG)

And Heres where i got JDK 16 (For Reproduction Purposes)
https://jdk.java.net/16/

tell me if there's anything else i need to include thanks

**Comment by Blobanium** [comment]
i accidentally hit enter and it opened an issue without me finishing hang on lemme edit

update: ok done

**Comment by Grayray75** [comment]
Known issue, see #13

**Comment by Blobanium** [comment]
ok then closing this issue as a duplicate.
