### ISSUE TITLE
CurseForge page request

### ISSUE THREAD

**Issue by NoComment1105** [CaffeineMC/hydrogen-fabric#28]
I know that curseforge is outdated and the modrinth is the thing now, but i run a minecraft server for my freinds on aternos and that only allows curseforge mods, so i would like to request a curseforge page, to try and help my server out as we are regularly running into lag issues when many people are online.
I understand if you dont want to do this, this quite a specfiic thing

**Comment by triphora** [comment]
Modrinth mods are now allowed on Aternos.

https://aternos.org/addons/a/modrinthfabric/AZomiSrC

**Comment by NoComment1105** [comment]
Excellent, I dont use aternos much anymore but thank you for letting me know!
