### ISSUE TITLE
Bug... Oftifabric + hydrogen mod

### ISSUE THREAD

**Issue by SevenIsNotNumber** [CaffeineMC/hydrogen-fabric#29]
After loading is completed, minecraft will load, then it will go back to splash screen again...

**Comment by LucilleTea** [comment]
Duplicate of #20

**Comment by SevenIsNotNumber** [comment]
> Duplicate of #20


Logs https://pastebin.pl/view/8c7ad6cd

**Comment by SevenIsNotNumber** [comment]
I use a minecraft java launcher for android....

**Comment by SevenIsNotNumber** [comment]
Btw thanks for respond
