### ISSUE TITLE
Hydrogen is incompatible with Tech Reborn

### ISSUE THREAD

**Issue by watersofnazareth** [CaffeineMC/hydrogen-fabric#3]
Crash Log:
https://pastebin.pl/view/683b03a1
Latest.log:
https://pastebin.pl/view/60e8f33d

Seems to turn a machine into air

**Comment by jellysquid3** [comment]
This was fixed a few days ago with https://github.com/jellysquid3/hydrogen-fabric/commit/b691a6892f17a5f93aa8fb1f8f0605a036138ce8. Just needs to be packaged into a new release.
