### ISSUE TITLE
cant join bungeecord servers

### ISSUE THREAD

**Issue by deltanedas** [CaffeineMC/hydrogen-fabric#31]
With Minecraft 1.16.5, Fabric Loader 0.11.1, Fabric API 0.30.3+1.16, Hydrogen 0.2-SNAPSHOT I cannot connect to BungeeCord servers (tried cubecraft.net).

After encrypting, I am disconnected with the error being
```
[Netty Epoll Client IO #0/WARN]: Received invalid channel identifier "BungeeCord" from connection net.minecraft.class_2535@2e55d77f
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:BungeeCord
```
and others for `FML`, `FML|HS`, `FORGE` in place of BungeeCord

original fapi issue: https://github.com/FabricMC/fabric/issues/1347

**Comment by jellysquid3** [comment]
Can you please upload a complete log file? One fragment of the log output (which might be a red herring, anyways) is not enough to diagnose this issue.

**Comment by deltanedas** [comment]
this also requires justmap (used 1.2.19) to disconnect

log: [latest.log](https://github.com/CaffeineMC/hydrogen-fabric/files/6096250/latest.log)

**Comment by deltanedas** [comment]
damn, justmap caused it alone.

i mustve removed justmap and hydrogen at the same time to come to the conclusion that hydrogen caused it, sorry guys!
