### ISSUE TITLE
Hotbars saved without Hydrogen are not displayed with Hydrogen

### ISSUE THREAD

**Issue by 2mal3** [CaffeineMC/hydrogen-fabric#32]
Hotbars that I saved before using Hydrogen are no longer displayed and cannot be loaded. However, if you save a hotbar while using Hydrogen, it displays normally. As soon as you start Minecraft without Hydrogen all saved hotbars are displayed normally again. However, if you saved a hotbar while using Hydrogen, all others saved hotbars, except the one you just saved, are gone when you start Minecraft without Hydrogen.

Fabric loader 0.11.2 1.16.5
Fabric API 0.31.0+1.16
Hydrogen 0.2.0

**Comment by jellysquid3** [comment]
This issue is quite old, and I haven't been able to reproduce it in the latest release for MC 1.17. If you think this still occurs, please re-open the issue.
