### ISSUE TITLE
Tech Reborn's Iron Alloy Furnace crashes with Hydrogen

### ISSUE THREAD

**Issue by Neubulae** [CaffeineMC/hydrogen-fabric#4]
[crash-2020-09-12_10.57.37-client.txt](https://github.com/jellysquid3/hydrogen-fabric/files/5212096/crash-2020-09-12_10.57.37-client.txt)
Hydrogen Version: Latest commit.

**Comment by Neubulae** [comment]
[crash-2020-09-12_11.05.16-client.txt](https://github.com/jellysquid3/hydrogen-fabric/files/5212108/crash-2020-09-12_11.05.16-client.txt)
This happens when I try to *place* other machinery down. The log I provided earlier happens when I try to *load* the world.

**Comment by jellysquid3** [comment]
Should be fixed in latest HEAD.
