### ISSUE TITLE
Hydrogen causes Minecraft boot loop with certain mods 

### ISSUE THREAD

**Issue by CatboyVenti** [CaffeineMC/hydrogen-fabric#41]
Mods used:
![image](https://user-images.githubusercontent.com/85883963/121899576-758ec000-cd1c-11eb-9b34-44c05726899f.png)

How to reproduce:
- Place these mods together in mods folder
- Run Fabric 1.16.5 latest
- Launch

**Comment by GamerTygoNL** [comment]
OptiFine is the problem

**Comment by jellysquid3** [comment]
OptiFine is not supported, and you haven't provided any crash logs to help diagnose this problem.

**Comment by CatboyVenti** [comment]
I’ll reinstall the mods  tomorrow and post crash logs for you, if that’s fine.
