### ISSUE TITLE
Game stuck loading

### ISSUE THREAD

**Issue by Minionguyjpro** [CaffeineMC/hydrogen-fabric#43]
Using Hydrogen by me let the game being stuck on loading.
Im using:
OS: Windows 10
Java/JDK: Adoptopenjdk 16.0.1
Minecraft: 1.17

**Comment by MeeniMc** [comment]
Are you using Optifine/optifabric by any chance? 

Hydrogen is incompatible with Optifine.

**Comment by Minionguyjpro** [comment]
Yeah that right, but why doesnt it work?

**Comment by amnotbananaama** [comment]
Closing as a duplicate of #20. See there:
> The issue here looks to be that OptiFine is messing around with block models after they've been loaded (which seems like a violation of contract here given this data should be immutable) and this causes Hydrogen to throw an error.
