### ISSUE TITLE
1.17.1 compatibility

### ISSUE THREAD

**Issue by RealTriassic** [CaffeineMC/hydrogen-fabric#48]
Currently, Hydrogen is not compatible with Minecraft 1.17.1, it will crash whilst starting Minecraft with:

Could not find required mod: hydrogen requires {minecraft @ [1.17]}
Creating Empty clause ?

**Comment by Foxite** [comment]
Replacing "1.17" with "1.17.x" in fabric.mod.json ***seems*** to work, but don't blame the devs if it causes issues.

I'll update here if I find any problems with it before a proper update is released.

**Comment by amnotbananaama** [comment]
Closing with d97afe77f598d0524319d77bdd220f407206a4a4
