### ISSUE TITLE
Not compatible with mod Better Nether

### ISSUE THREAD

**Issue by linzexin022** [CaffeineMC/hydrogen-fabric#5]
Minecraft version: 1.16.3
Hydrogen version: 1.16.2-0.1.1
Better Nether: 1.16.3-4.1.2
Fabric API version: 0.22.0+build.408-1.16
Fabric Loader version: 0.10.0+build.208

Test with only mod Better Nether, Hydrogen and Fabric API.

Here's the crash reports:
[crash-2020-09-29_16.47.17-client.txt](https://github.com/jellysquid3/hydrogen-fabric/files/5297658/crash-2020-09-29_16.47.17-client.txt)

**Comment by Snivine** [comment]
I know I'm not a developer but, what's your java version? just in curiosity because "java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by '<mod_name>'!" happened to me with a lot of mods only if I have any java +8 version

**Comment by ramidzkh** [comment]
This looks like the line causing the problem with Hydrogen, https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/blocks/BlockNeonEquisetum.java#L58

**Comment by paulevsGitch** [comment]
> This looks like the line causing the problem with Hydrogen, https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/blocks/BlockNeonEquisetum.java#L58

This shouldn't be problem source, as it is default MC functions to set default blockstates (many vanilla blocks and modded blocks use this function). Looks like problem is somewhere in block init order

**Comment by jellysquid3** [comment]
This should now be fixed in HEAD.
