### ISSUE TITLE
Incompatible with Architect's Palette

### ISSUE THREAD

**Issue by SplendidAlakey** [CaffeineMC/hydrogen-fabric#53]
**MC** 1.17.1
**Fabric API** 0.37.0
**Hydrogen** fabric-mc1.17.1-0.3
**Architect's Palette** fabric-port-1.2

It is impossible to launch the game when AP is present. No crash log is being generated, but here is the [latest.log](https://github.com/CaffeineMC/hydrogen-fabric/files/6851520/latest.log).

Another user has filed a report on AP's GitHub [here](https://github.com/jsburger/Architects-Palette/issues/13), but received no response in over a month. Is it something that can be fixed on the Hydrogen's side? If not, I will consider AP unmaintained and remove from my modlist. 

Edit: there's also a thread on fabric specific port https://github.com/Slomaxonical-907/Architects-Palette-Fabric/issues/2, I didn't notice that the one I linked is actually for Forge. Either way, both versions conflict.

**Comment by magneticflux-** [comment]
Possible duplicate of https://github.com/CaffeineMC/hydrogen-fabric/issues/19

**Comment by SplendidAlakey** [comment]
Was fixed a long time ago on Architect's Palette side. The fixed version is up on CF (1.3).
