### ISSUE TITLE
Incompatibiltiy with Opfitine/Optifabric

### ISSUE THREAD

**Issue by ghost** [CaffeineMC/hydrogen-fabric#56]
Mod versions:
Fabric Installer 0.7.4
Fabric Api 0.37.1+1.16
Hydrogen Fabric MC1.16.5-0.2
Optifine 1.16.5 HD U G8
OptiFabric 1.11.9

Issue in question: when game launches, you are stuck in the main menu screen while it keeps reloading. After the first or second reload, it switches to the default minecraft texturepack. Video below shows the infinite reloading

Steps to reproduce: Download mods stated above, drop them in .minecraft/mods, launch fabric installer, select version 1.16.5 to be installed, after that is done launch minecraft select the fabric version and click play. 

It's not really unexpected as Sodium and Lithium already aren't compatible with Optifine/OptiFabric, but it isn't noted on Modrinth. I doubt you would want to make it compatible seen how the other two aren't, so just adding a known incompatibility in the Modrinth description would suffice. 

https://user-images.githubusercontent.com/47089475/129499301-0ffba51c-581e-4615-a414-0218e79839a8.mp4

**Comment by Leo40Git** [comment]
This has already been fixed in Hydrogen versions for 1.17 (a `breaks` clause was added for OptiFabric, meaning having both mods installed will stop the game from loading way earlier).

**Comment by jellysquid3** [comment]
This won't be fixed. Newer versions of Hydrogen simply crash the game earlier during startup if OptiFine is detected.
