### ISSUE TITLE
Saved Hotbar Slot Disappeared

### ISSUE THREAD

**Issue by syadisntsomething** [CaffeineMC/hydrogen-fabric#57]
Hello, I'm actually pretty new to this mod, so i dont know if this has happened before, but in my case, my saved hotbar slot just disappeared even though i checked my hotbar.nbt file. please fix this if this is a bug or if it is something else please let me know

![png1](https://user-images.githubusercontent.com/90105610/132101708-2b5056ec-8d7c-405b-9435-e9cab270149c.PNG)
![png2](https://user-images.githubusercontent.com/90105610/132101710-19271acb-0f88-4c28-8691-2135c20aad7b.PNG)
![png3](https://user-images.githubusercontent.com/90105610/132101711-c6ca3143-f562-4413-b616-398ff075e6f2.PNG)

**Comment by itsdinkd** [comment]
imagine thinking hydrogen would do this and then opening up a nbt in notepad++ lol

**Comment by syadisntsomething** [comment]
> imagine thinking hydrogen would do this and then opening up a nbt in notepad++ lol

![image](https://user-images.githubusercontent.com/90105610/133883150-64eb525d-57ce-4b23-a203-e6db07bc1908.png)

**Comment by syadisntsomething** [comment]
> > imagine thinking hydrogen would do this and then opening up a nbt in notepad++ lol
> 
> ![image](https://user-images.githubusercontent.com/90105610/133883150-64eb525d-57ce-4b23-a203-e6db07bc1908.png)

there with the nbt editor, my bad
