### ISSUE TITLE
1.18.1?

### ISSUE THREAD

**Issue by HughSparks** [CaffeineMC/hydrogen-fabric#64]
Just wondering if there is an alpha build or jenkins to follow?

**Comment by MeeniMc** [comment]
Edit the .jar and remove the version lock on the 1.18 build, it works. I won't update the PR until there is a significant change required in H, or 1.18.1 is released.

**Comment by tersilesox** [comment]
How would you do this?

**Comment by MeeniMc** [comment]
I updated the PR, see build.91 if you want to try it.
